# Generated by Django 3.1.4 on 2023-04-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20230428_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='variation',
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
