version: "3"

services:
  #   ____    _    ____ _  _______ _   _ ____
  #  | __ )  / \  / ___| |/ / ____| \ | |  _ \
  #  |  _ \ / _ \| |   | ' /|  _| |  \| | | | |
  #  | |_) / ___ \ |___| . \| |___| |\  | |_| |
  #  |____/_/   \_\____|_|\_\_____|_| \_|____/
  #

  db:
    container_name: "postgres"
    image: postgres:13-alpine
    expose:
      - "5432"
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data


  backend:
    container_name: "backend"
    build: ./back-end
    command: >
      sh -c "
            python3 manage.py makemigrations &&
            python3 manage.py migrate &&
            python3 manage.py runserver 0.0.0.0:8000
            "
    expose:
      - 8000
    ports:
      - "8000:8000"

    env_file:
      - ./.env
    volumes:
      - static:/static
      - aws:/aws
      - ./back-end/:/back-end



  #   ___ ___  ___  _  _ _____ ___ _  _ ___
  #  | __| _ \/ _ \| \| |_   _| __| \| |   \
  #  | _||   / (_) | .` | | | | _|| .` | |) |
  #  |_| |_|_\\___/|_|\_| |_| |___|_|\_|___/
  #
  frontend:
      container_name: "frontend"
      build: ./front-end
      volumes:
       - ./front-end/:/app
       - /app/node_modules
      ports:
        - '3000:3000'
      stdin_open: true
      tty: true
  # #   _   _  ____ ___ _   ___  __
  # #  | \ | |/ ___|_ _| \ | \ \/ /
  # #  |  \| | |  _ | ||  \| |\  /
  # #  | |\  | |_| || || |\  |/  \
  # #  |_| \_|\____|___|_| \_/_/\_\
  # #
  # nginx:
  #   container_name: nginx
  #   restart: always
  #   build:
  #     context: .
  #     dockerfile: nginx/Dockerfile
  #   ports:
  #     - 443:80
  #     - 80:80
  #   depends_on:
  #     - backend
  #   volumes:
  #     - static:/static
  #     - frontend_build:/frontend_build
volumes:
  frontend_build: {} 
  static: {}
  aws: {}
