# Generated by Django 3.1.4 on 2023-03-14 08:30

import apps.config.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=apps.config.fields.TrimCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.SmallIntegerField(blank=True, choices=[('admin', 'Admin'), ('customer', 'customer')], default=0, null=True),
        ),
    ]
