# Generated by Django 3.1.4 on 2023-03-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20230314_0830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_phone_confirmed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=255, null=True),
        ),
    ]
