# Generated by Django 3.1.4 on 2023-07-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20230412_1609'),
        ('user', '0005_user_wish_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wish_list',
        ),
        migrations.AddField(
            model_name='user',
            name='wish_list',
            field=models.ManyToManyField(blank=True, related_name='users_wishing', to='store.Products'),
        ),
    ]
