# Generated by Django 3.1.4 on 2023-03-15 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('sports', 'sports'), ('kids', 'kids'), ('girls', 'girls'), ('boys', 'boys')], max_length=255, unique=True),
        ),
    ]
