# Generated by Django 3.1.4 on 2023-04-12 15:57

import apps.store.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20230316_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.store.utils.category_image_file_path),
        ),
        migrations.AddField(
            model_name='products',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=apps.store.utils.products_image_file_path),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cat_products', to='store.category'),
        ),
    ]
