# Generated by Django 3.1.4 on 2023-04-11 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20230316_0918'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='carts.cart'),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='variation',
            field=models.ManyToManyField(blank=True, null=True, to='store.Variation'),
        ),
    ]
