# Generated by Django 3.1.4 on 2023-04-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_auto_20230428_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='quauntity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
