# Generated by Django 3.1.4 on 2023-07-20 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_auto_20230720_1135'),
        ('carts', '0006_auto_20230719_1653'),
    ]

    operations = [
    ]
